```mermaid
graph LR;
  n__Users_jamie_Coding_Sourceflow_run_analyzer_py["run_analyzer.py"];
  n__Users_jamie_Coding_Sourceflow_sourceflow___init___py["__init__.py"];
  n__Users_jamie_Coding_Sourceflow_sourceflow_main_py["main.py"];
  n__Users_jamie_Coding_Sourceflow_sourceflow_core_analyzer_py["analyzer.py"];
  n__Users_jamie_Coding_Sourceflow_sourceflow_core___init___py["__init__.py"];
  n__Users_jamie_Coding_Sourceflow_sourceflow_core_builder_py["builder.py"];
  n__Users_jamie_Coding_Sourceflow_sourceflow_core_explorer_py["explorer.py"];
  n__Users_jamie_Coding_Sourceflow_sourceflow_core_visualizer_py["visualizer.py"];
```